---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-ebs-claim
  namespace: ghanem
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: zghanem.aws/v1
kind: VolumeScaler
metadata:
  name: test-ebs-claim
  namespace: ghanem
spec:
  pvcName: test-ebs-claim
  threshold: "70%"
  scaleType: "percentage"
  scale: "30%"
  maxSize: 6Gi
# ---
# apiVersion: zghanem.aws/v1
# kind: VolumeScaler
# metadata:
#   name: test-ebs-claim
#   namespace: ghanem
# spec:
#   pvcName: test-ebs-claim
#   threshold: "70%"
#   scale: "2Gi"               # or "30%" for a percentage
#   scaleType: "fixed"         # "fixed" or "VolumeScaler"
#   cooldownPeriod: "10m"      #  format ("300s", "10m", "1h", etc.)
#   maxSize: "5Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-data-generator
  namespace: ghanem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-data-generator
  template:
    metadata:
      labels:
        app: test-data-generator
    spec:
      containers:
        - name: data-generator
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                echo "Generating data for test-ebs-claim..."
                dd if=/dev/urandom of=/data/new-file-$(date +%s).txt bs=1M count=50 2>/dev/null
                sleep 2
              done
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: test-ebs-claim
