# Default values for VolumeScaler chart

image:
  repository: public.ecr.aws/ghanem/volumescaler
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: Always

rbac:
  create: true
  serviceAccountName: pvc-resizer

daemonset:
  name: volumescaler-daemonset
  namespace: default
  labels: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: system-node-critical

sidecars: []  # Additional sidecars if needed

# Resources for container
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

pvcResizerEnv: []  # Additional environment variables if needed

# 
kubeletHostPath: /var/lib/kubelet
