# Default values for VolumeScaler chart

image:
  repository: public.ecr.aws/ghanem/volumescaler
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: Always

rbac:
  create: true
  serviceAccountName: pvc-resizer

daemonset:
  name: volumescaler-daemonset
  namespace: default
  labels: {}
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
  priorityClassName: system-node-critical

sidecars: []  # Additional sidecars if needed

# Resources for container
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

pvcResizerEnv: []  # Additional environment variables if needed
