name: Trivy Scanner - Container Images
on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 */24 * * *'

permissions:
  contents: read
  security-events: write # Update findings in security tab

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-matrix.outputs.result }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: set-matrix
        run: |
          MATRIX=$(yq '[{"repository": .image.repository, "tag": .appVersion}] + (.sidecars | map(.image)) | map(.repository + ":" + .tag) | . style="flow"' charts/volumescaler/values.yaml)
          if [[ -z "$MATRIX" || "$MATRIX" == "[]" ]]; then
            echo "No images found. Exiting."
            exit 1
          fi
          echo "result=$MATRIX" >> $GITHUB_OUTPUT

      - name: Debug Matrix Output
        run: |
          echo "Images: ${{ steps.set-matrix.outputs.result }}"

  trivy-scan:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.build-matrix.outputs.images || '["default:latest"]') }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubCI
          aws-region: us-east-1
          role-duration-seconds: 1800
          role-skip-session-tagging: true

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          
      - name: Pull container image
        run: docker pull ${{ matrix.image }}

      - name: Scan container image
        uses: aquasecurity/trivy-action@0.29.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          image-ref: '${{ matrix.image }}'
          output: 'results.sarif'
          format: 'sarif'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'results.sarif'